# Workflow to build and deploy site to AWS using Apex Up
name: deploy-production
on:
  push:
    branches: [ master ] 
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
          submodules: true  # Fetch Hugo themes
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
          hugo-version: 'latest'
    - name: Check 
      run: |
          which hugo
          which jq
    - name: Build Site Public with Hugo
      env: 
          PRODBTOKEN15331: ${{ secrets.PRODBTOKEN15331 }}
      run: |
          DT=`date +'%Y%m%d-%H%M%S'`
          HUGOBASEURL="https://logr.cogley.info"
          rm -rf data/holidays.json
          curl --silent https://pro.dbflex.net/secure/api/v2/15331/$PRODBTOKEN15331/Work%20Holiday/API%20Holidays/select.json | jq '.' > data/holidays.json
          git add .
          git diff-index --quiet HEAD || git commit -m "Logr update post $DT"
          git push origin master
          hugo --gc --minify --baseURL=$HUGOBASEURL
    - name: Deploy via Apex Up
      env:
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          UP_CONFIG: ${{ secrets.UP_CONFIG }}
      uses: apex/actions/up@v0.5.1
      with:
        stage: production 
    - name: Check folder contents
      run: |
          ls
          echo "====== PUBLIC ======"
          ls public
